DROP DATABASE IF EXISTS PHARMACYSYSTEM;
CREATE DATABASE IF NOT EXISTS PHARMACYSYSTEM;
USE PHARMACYSYSTEM;
SHOW DATABASES;


/*Doctor TABLE*/
DROP TABLE IF EXISTS DOCTOR;
CREATE TABLE IF NOT EXISTS DOCTOR(
DID VARCHAR (20),
Name VARCHAR (30),
Address VARCHAR (30),
Experiennce VARCHAR (20),

CONSTRAINT PRIMARY KEY(DID)
);
SHOW TABLES;
DESC DOCTOR;

#-----------------------------------------------


/*CUSTOMER TABLE*/
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE IF NOT EXISTS CUSTOMER(
CID VARCHAR (20),
Name VARCHAR (30),
address VARCHAR (30),
DID VARCHAR (20),

CONSTRAINT PRIMARY KEY(CID),
CONSTRAINT FOREIGN KEY(DID) REFERENCES DOCTOR(DID) ON DELETE CASCADE ON UPDATE CASCADE


);
SHOW TABLES;
DESC CUSTOMER;

#-----------------------------------------------


/*PAYMENT TABLE*/
DROP TABLE IF EXISTS PAYMENT;
CREATE TABLE IF NOT EXISTS PAYMENT(
PID VARCHAR (20),
CID VARCHAR (20),
Productname VARCHAR (20),
Bank VARCHAR (30),
accountno VARCHAR (30),


CONSTRAINT PRIMARY KEY(PID),
CONSTRAINT FOREIGN KEY(CID) REFERENCES CUSTOMER(CID) ON DELETE CASCADE ON UPDATE CASCADE
);
SHOW TABLES;
DESC PAYMENT;

#-----------------------------------------------





/*Admin TABLE*/

DROP TABLE IF EXISTS ADMIN;
CREATE TABLE IF NOT EXISTS
ADMIN(
ADMINID VARCHAR (20),
USERNAME VARCHAR (30),
PASSWORD VARCHAR (20),

CONSTRAINT PRIMARY KEY(ADMINID)
);
SHOW TABLES;
DESC ADMIN;

#-----------------------------------------------

/*Dilivery Service TABLE*/

DROP TABLE IF EXISTS DILEVARY;
CREATE TABLE IF NOT EXISTS DILEVARY(
DSID VARCHAR (20),
DSNAME VARCHAR (30),


CONSTRAINT PRIMARY KEY(DSID)
);
SHOW TABLES;
DESC DILEVARY;

#-----------------------------------------------
/*ITEM TABLE*/

DROP TABLE IF EXISTS ITEM;
CREATE TABLE IF NOT EXISTS ITEM(
PCODE VARCHAR (20),
NAME VARCHAR (30),
DISCRIPTION VARCHAR (30),
QTY INT(10),
PRICE DECIMAL(6,2) ,

CONSTRAINT PRIMARY KEY(PCODE)
);
SHOW TABLES;
DESC ITEM;

#-----------------------------------------------
/*ORDER TABLE*/

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE IF NOT EXISTS ORDERS(
OID VARCHAR (20),
CID VARCHAR (20),
DSID VARCHAR (20),
DATE VARCHAR (30),
TIME VARCHAR (30),


CONSTRAINT PRIMARY KEY(OID),
CONSTRAINT FOREIGN KEY(DSID) REFERENCES DILEVARY(DSID) ON DELETE CASCADE ON UPDATE CASCADE ,
CONSTRAINT FOREIGN KEY(CID) REFERENCES CUSTOMER(CID) ON DELETE CASCADE ON UPDATE CASCADE

);

SHOW TABLES;
DESC ORDERS;


#-----------------------------------------------
/*ORDERDETAILS TABLE*/

DROP TABLE IF EXISTS ORDERDETAILS;
CREATE TABLE IF NOT EXISTS ORDERDETAILS(
OID VARCHAR (20),
PCODE VARCHAR (20),
CID VARCHAR (20),
DATE VARCHAR (30),
TIME VARCHAR (30),


CONSTRAINT PRIMARY KEY(OID,PCODE),
CONSTRAINT FOREIGN KEY(CID) REFERENCES CUSTOMER(CID) ON DELETE CASCADE ON UPDATE CASCADE ,
CONSTRAINT FOREIGN KEY(OID) REFERENCES ORDERS(OID) ON DELETE CASCADE ON UPDATE CASCADE ,
CONSTRAINT FOREIGN KEY(PCODE) REFERENCES ITEM(PCODE) ON DELETE CASCADE ON UPDATE CASCADE

);
SHOW TABLES;
DESC ORDERS;

